version: "3.9"
name: humblib-dev
services:
  backend:
    build:
      context: ./
      args:
        ports: 3000
    environment:
      - RUN_ENV=dev
      - DATABASE_HOST=db
    ports:
      - "3000:3000"
    links:
      - db
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - type: bind
        source: .
        target: /app
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=humblib
      - POSTGRES_PASSWORD=humblib
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
